### ISSUE TITLE
Cannot find module 'perf_hooks' from nanotiming

### ISSUE THREAD

**Issue by kristoferjoseph** [yoshuawuyts/nanotiming#19]
I am running a standalone browserify build that is not completing because of this error.
`Error: Cannot find module 'perf_hooks' from '.../node_modules/nanotiming'`
https://github.com/choojs/nanotiming/blob/master/index.js#L6

**Comment by kristoferjoseph** [comment]
I upgraded to the latest node version 8.9.4 and the error changed to something like
`Error:  lstat perf_hooks is not a file or directory`

if i create a file named 'perf_hooks' at the path listed in the error it works as expected :/

**Comment by kristoferjoseph** [comment]
Looks like wrapping the `require('perf_hooks')` in a try catch isn't enough.
Error causes `browserify` standalone build to fail
Error: Cannot find module 'perf_hooks' from '.../node_modules/nanotiming'

**Comment by yoshuawuyts** [comment]
Tested this on node 6, 8 and 9 today, and it seems the try...catch should be enough. Is this perhaps related to a bundler you're running on your end perhaps?

**Comment by goto-bus-stop** [comment]
https://github.com/browserify/browserify/pull/1815 should fix I think?

**Comment by xiaoanne** [comment]
I got this fixed by upgrade node version to 8.11.2:

nvm install v8.11.2
