### ISSUE TITLE
Package and dependents broken by localStorage when sandboxed

### ISSUE THREAD

**Issue by m59peacemaker** [yoshuawuyts/nanotiming#6]
I happened to be on requirebin and required `nanobus`, and it is broken with the following error:

`node_modules/nanotiming/index.js:9 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.`

How do you feel about having a try/catch around the localStorage access?

**Comment by yoshuawuyts** [comment]
Oh oops, yeah that'd be good. PR welcome! :D
